### ISSUE TITLE
Theme icons are not displayed as seen in screenshots

### ISSUE THREAD

**Issue by bohoffi** [angular-experts-io/terminal#1]
Hi @tomastrajan 
I've followed [Kevins post](https://angularexperts.io/blog/the-ultimate-terminal) for setting up Hyper in combination with fish, oh-my-posh and the Angularic theme using `Fira Code` as font.

![image](https://user-images.githubusercontent.com/9944566/208905461-76dd4c76-6a5c-4cc6-951d-29a5e9c9203a.png)

As you can see in the screenshot the segment show up but I cannot get the icons to work.

My setup:
* MacOS: 13.1
* Hyper: 3.3.0
* oh-my-posh: 12.28.0
* fish: 3.5.1

**Comment by tomastrajan** [comment]
Hi @bohoffi , make sure you use the `Nerd Font` version of any font you pick.
In your case that would be `FiraCode Nerd Font` [link](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip)

[Nerd Fonts](https://www.nerdfonts.com/font-downloads)


If you already use that one make sure to set it as font of your console / terminal.

Also check other [troubleshooting](https://www.nerdfonts.com/font-downloads) info 😉

**Comment by bohoffi** [comment]
Thanks for the clarification. I took `Nerd Font` as a "slang" for a collection of specific font - and not as  sub class of a specific font.

Got it working now
![image](https://user-images.githubusercontent.com/9944566/208940157-0ae1ba4d-6e4e-4357-aa69-2d6fc9a6d68e.png)
